# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trust' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trust
  flutter_application_path = '/Users/bassemqoulta/Desktop/FlutterChannel/my_flutter'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)


end
